baseURL = "https://SlRvb.github.io"
languageCode = "en-us"
pygmentsUseClasses = true
ignoreFiles = ["/content/0_Technical/0_Templates/*"]

[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 2
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        style = "dracula"
        tabWidth = 4